### ISSUE TITLE
Data fetching not working / 数据无法更新

### ISSUE THREAD

**Issue by mma345** [spencerwooo/PaimonMenuBar#22]
it works fine before, but now it just stop refresh and even if the cookie is correct, it still sats that it is wrong, maybe something changes in the mihoyo's website i.e miyoushe and hoyo lab.

**Comment by spencerwooo** [comment]
因为 API 触发了验证码，登陆米游社点击「我的」-「我的角色」即可看到。手动验证之后即可重新获取数据。但是这个验证码会偶尔由于频繁调用 API 而触发，所以建议 app 中设置更大间隔的刷新时间（直到找到更好的解决方法）。

It's because the API is captcha-ed. So login to your HoyoLab APP and navigate to characters. You'll see and manually go through the captcha, which re-enables the API. The captcha is triggered when the API is called too frequent, so set a larger refresh interval in PaimonMenuBar - until we find a better solution.

**Comment by spencerwooo** [comment]
Should be working better now in [v1.12.126](https://github.com/spencerwooo/PaimonMenuBar/releases/tag/v1.12.126)
